version: '3.9'

services:
  backend:
    build: ./backend
    container_name: chatbot_backend
    env_file:
      - ./backend/.env
    restart: always
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    container_name: chatbot_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: chatbot_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do
        certbot renew --webroot -w /var/lib/letsencrypt;
        sleep 12h & wait $${!};
      done"

volumes:
  certbot-etc:
  certbot-var:
